spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_auth_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:

    signing:
      private-key: ${JWT_PRIVATE_KEY:classpath:private.pem}
      public-key: ${JWT_PUBLIC_KEY:classpath:public.pem}
      key-id: sign-key-2026-1

    encryption:
      private-key: ${JWT_ENCRYPTION_PRIVATE_KEY:classpath:encryption-private.pem}
      public-key: ${JWT_ENCRYPTION_PUBLIC_KEY:classpath:encryption-public.pem}
      key-id: enc-key-2026-1

    issuer: demo-service
    audience: demo-clients

    access-token:
      ttl-minutes: 15

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/