 CREATE TABLE auth_user(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_code VARCHAR(255) ,
        first_name VARCHAR(255),
        last_name VARCHAR(255),
        email VARCHAR(255) NOT NULL ,
        password VARCHAR(255),
        mobile_number VARCHAR(255) NOT NULL ,
        date_of_birth DATE NOT NULL,

        created_at      TIMESTAMP WITHOUT TIME ZONE,
        created_by      BIGINT,
        updated_at      TIMESTAMP WITHOUT TIME ZONE,
        status          CHAR(1) DEFAULT 'Y',
        deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_auth_user PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_mobile UNIQUE (mobile_number)
 )