CREATE TABLE outbox_events (

           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

           event_id UUID NOT NULL UNIQUE,
           aggregate_type VARCHAR(100) NOT NULL,
           aggregate_id BIGINT NOT NULL,

           event_type VARCHAR(150) NOT NULL,
           event_key VARCHAR(255) NOT NULL,
           payload JSONB NOT NULL,

           created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
           published_at TIMESTAMP WITHOUT TIME ZONE,

           retry_count INTEGER NOT NULL DEFAULT 0,
           status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

           CONSTRAINT pk_outbox_events PRIMARY KEY (id),
           CONSTRAINT chk_outbox_events_retry_count CHECK (retry_count >= 0),

           CONSTRAINT chk_outbox_events_status
               CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX idx_outbox_events_status_created_at
    ON outbox_events (status, created_at);

CREATE INDEX idx_outbox_events_aggregate
    ON outbox_events (aggregate_type, aggregate_id);

CREATE INDEX idx_outbox_events_event_type
    ON outbox_events (event_type);
