CREATE TABLE error_logs(
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       journey_id VARCHAR(100),
       error_type VARCHAR(255),
       error_message TEXT,
       stack_trace TEXT,
       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

       CONSTRAINT pk_error_logs PRIMARY KEY (id)
);