CREATE TABLE refresh_tokens (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        token VARCHAR(255),
        user_id BIGINT,
        expires_at TIMESTAMP WITHOUT TIME ZONE,
        revoked_at TIMESTAMP WITHOUT TIME ZONE,
        created_by_ip_address VARCHAR(255),
        created_at TIMESTAMP WITHOUT TIME ZONE,
        updated_at TIMESTAMP WITHOUT TIME ZONE,

        CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);
