CREATE TABLE user_events(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        event_id VARCHAR(255) NOT NULL,
        event_type VARCHAR(255),
        event_key VARCHAR(255),
        request_payload JSONB,

        created_at      TIMESTAMP WITHOUT TIME ZONE,
        created_by      BIGINT,
        updated_at      TIMESTAMP WITHOUT TIME ZONE,
        status          CHAR(1) DEFAULT 'Y',
        deleted_at      TIMESTAMP WITHOUT TIME ZONE,

        CONSTRAINT pk_user_events PRIMARY KEY (id),
        CONSTRAINT uk_user_events_event_id UNIQUE (event_id)
);
