CREATE TABLE brands (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        brand_code VARCHAR(255) NOT NULL,
                        name VARCHAR(255) NOT NULL,
                        slug VARCHAR(255) NOT NULL,
                        description VARCHAR(255),

                        created_at TIMESTAMP WITHOUT TIME ZONE,
                        created_by BIGINT,
                        updated_at TIMESTAMP WITHOUT TIME ZONE,
                        status CHAR(1) DEFAULT 'Y',
                        deleted_at TIMESTAMP WITHOUT TIME ZONE,

                        CONSTRAINT pk_brands PRIMARY KEY (id),
                        CONSTRAINT uk_brands_brand_code UNIQUE (brand_code),
                        CONSTRAINT uk_brands_name UNIQUE (name),
                        CONSTRAINT uk_brands_slug UNIQUE (slug)
);