CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          product_code VARCHAR(255) NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          slug VARCHAR(255) NOT NULL,
                          description TEXT,
                          brand_id BIGINT NOT NULL,

                          created_at TIMESTAMP WITHOUT TIME ZONE,
                          created_by BIGINT,
                          updated_at TIMESTAMP WITHOUT TIME ZONE,
                          status CHAR(1) DEFAULT 'Y',
                          deleted_at TIMESTAMP WITHOUT TIME ZONE,

                          CONSTRAINT pk_products PRIMARY KEY (id),

                          CONSTRAINT uk_products_product_code
                              UNIQUE (product_code),

                          CONSTRAINT uk_products_slug
                              UNIQUE (slug),

                          CONSTRAINT fk_products_brand
                              FOREIGN KEY (brand_id)
                                  REFERENCES brands(id)
);