CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          category_code VARCHAR(50) NOT NULL,
                          name VARCHAR(150) NOT NULL,
                          slug VARCHAR(180) NOT NULL,
                          description TEXT,
                          parent_id BIGINT,

                          created_at TIMESTAMP WITHOUT TIME ZONE,
                          created_by BIGINT,
                          updated_at TIMESTAMP WITHOUT TIME ZONE,
                          status CHAR(1) DEFAULT 'Y',
                          deleted_at TIMESTAMP WITHOUT TIME ZONE,

                          CONSTRAINT pk_category PRIMARY KEY (id),

                          CONSTRAINT uk_category_category_code
                              UNIQUE (category_code),

                          CONSTRAINT uk_category_slug
                              UNIQUE (slug),

                          CONSTRAINT fk_category_parent
                              FOREIGN KEY (parent_id)
                                  REFERENCES category(id)
);