CREATE TABLE product_variants (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  sku VARCHAR(255) NOT NULL,
                                  product_id BIGINT NOT NULL,
                                  barcode VARCHAR(255),

                                  created_at TIMESTAMP WITHOUT TIME ZONE,
                                  created_by BIGINT,
                                  updated_at TIMESTAMP WITHOUT TIME ZONE,
                                  status CHAR(1) DEFAULT 'Y',
                                  deleted_at TIMESTAMP WITHOUT TIME ZONE,

                                  CONSTRAINT pk_product_variants PRIMARY KEY (id),

                                  CONSTRAINT uk_product_variants_sku
                                      UNIQUE (sku),

                                  CONSTRAINT fk_product_variants_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES products(id)
);