CREATE TABLE product_category (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  product_id BIGINT,
                                  category_id BIGINT,

                                  created_at TIMESTAMP WITHOUT TIME ZONE,
                                  created_by BIGINT,
                                  updated_at TIMESTAMP WITHOUT TIME ZONE,
                                  status CHAR(1) DEFAULT 'Y',
                                  deleted_at TIMESTAMP WITHOUT TIME ZONE,

                                  CONSTRAINT pk_product_category PRIMARY KEY (id),

                                  CONSTRAINT fk_product_category_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES products(id),

                                  CONSTRAINT fk_product_category_category
                                      FOREIGN KEY (category_id)
                                          REFERENCES category(id)
);