CREATE TABLE product_media (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               product_id BIGINT NOT NULL,
                               variant_id BIGINT,
                               media_type VARCHAR(255) NOT NULL,
                               media_url VARCHAR(255) NOT NULL,
                               alt_text VARCHAR(255),
                               sort_order INTEGER,
                               is_primary BOOLEAN,

                               created_at TIMESTAMP WITHOUT TIME ZONE,
                               created_by BIGINT,
                               updated_at TIMESTAMP WITHOUT TIME ZONE,
                               status CHAR(1) DEFAULT 'Y',
                               deleted_at TIMESTAMP WITHOUT TIME ZONE,

                               CONSTRAINT pk_product_media PRIMARY KEY (id),

                               CONSTRAINT fk_product_media_product
                                   FOREIGN KEY (product_id)
                                       REFERENCES products(id),

                               CONSTRAINT fk_product_media_variant
                                   FOREIGN KEY (variant_id)
                                       REFERENCES product_variants(id)
);