CREATE TABLE attribute (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           code VARCHAR(255) NOT NULL,
                           name VARCHAR(255),

                           created_at TIMESTAMP WITHOUT TIME ZONE,
                           created_by BIGINT,
                           updated_at TIMESTAMP WITHOUT TIME ZONE,
                           status CHAR(1) DEFAULT 'Y',
                           deleted_at TIMESTAMP WITHOUT TIME ZONE,

                           CONSTRAINT pk_attribute PRIMARY KEY (id)
);
