CREATE TABLE attribute_values (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  attribute_id BIGINT NOT NULL,
                                  code VARCHAR(255) NOT NULL,
                                  value VARCHAR(255) NOT NULL,
                                  sort_order INTEGER,

                                  created_at TIMESTAMP WITHOUT TIME ZONE,
                                  created_by BIGINT,
                                  updated_at TIMESTAMP WITHOUT TIME ZONE,
                                  status CHAR(1) DEFAULT 'Y',
                                  deleted_at TIMESTAMP WITHOUT TIME ZONE,

                                  CONSTRAINT pk_attribute_values PRIMARY KEY (id),

                                  CONSTRAINT fk_attribute_values_attribute
                                      FOREIGN KEY (attribute_id)
                                          REFERENCES attribute(id)
);