CREATE TABLE variant_attribute_value (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         variant_id BIGINT,
                                         attribute_value_id BIGINT,

                                         created_at TIMESTAMP WITHOUT TIME ZONE,
                                         created_by BIGINT,
                                         updated_at TIMESTAMP WITHOUT TIME ZONE,
                                         status CHAR(1) DEFAULT 'Y',
                                         deleted_at TIMESTAMP WITHOUT TIME ZONE,

                                         CONSTRAINT pk_variant_attribute_value PRIMARY KEY (id),

                                         CONSTRAINT fk_variant_attribute_value_variant
                                             FOREIGN KEY (variant_id)
                                                 REFERENCES product_variants(id),

                                         CONSTRAINT fk_variant_attribute_value_attribute_value
                                             FOREIGN KEY (attribute_value_id)
                                                 REFERENCES attribute_values(id),

                                         CONSTRAINT uk_variant_attribute_value
                                             UNIQUE (variant_id, attribute_value_id)
);