 CREATE TABLE auth_users(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_name VARCHAR(255),
        email_id VARCHAR(255),
        password VARCHAR(255),
    CONSTRAINT pk_auth_users PRIMARY KEY (id)
 )