CREATE TABLE roles(
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255),

          created_at      TIMESTAMP WITHOUT TIME ZONE,
          created_by      BIGINT,
          updated_at      TIMESTAMP WITHOUT TIME ZONE,
          status          CHAR(1) DEFAULT 'Y',
          deleted_at      TIMESTAMP WITHOUT TIME ZONE,
          CONSTRAINT pk_roles PRIMARY KEY (id),
          CONSTRAINT uk_roles_name UNIQUE (name)
)