CREATE TABLE user_roles(
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          user_id BIGINT NOT NULL,
          role_id BIGINT NOT NULL,
          created_at      TIMESTAMP WITHOUT TIME ZONE,
          created_by      BIGINT,
          updated_at      TIMESTAMP WITHOUT TIME ZONE,
          status          CHAR(1) DEFAULT 'Y',
          deleted_at      TIMESTAMP WITHOUT TIME ZONE,

          CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id),
          CONSTRAINT fk_user_roles FOREIGN KEY (role_id) REFERENCES roles(id),

          CONSTRAINT pk_user_roles PRIMARY KEY (id)
)